function goToLink(searchName) {
    window.location.href = searchName;
}

// Alternatively, you can use JavaScript to handle the click event and navigate to the desired URL.
var logoLink = document.querySelector('.logo');
logoLink.addEventListener('click', function() {
    // Replace 'your-desired-url' with the actual URL you want to navigate to
    goToLink("https://inkycattt.github.io/Ink/"0
});
